-- Copy and paste this SQL into your Supabase SQL Editor to create the users table

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('basic', 'pro', 'advanced', 'enterprise')),
  hotel_name TEXT,
  max_radius INTEGER DEFAULT 5,
  allowed_city TEXT,
  address TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  password TEXT NOT NULL
);

-- Enable Row Level Security (RLS) is recommended, but for now we can leave it open 
-- or create a policy if you want strict security.
-- For simple internal use as requested (admin only on laptop), this is fine.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Allow read/write access to everyone (since we are handling auth in the app code for now)
-- WARNING: In a real production app with public users, you would want stricter policies.
CREATE POLICY "Enable all access for all users" ON users FOR ALL USING (true) WITH CHECK (true);

-- Optional: Insert initial Admin user if needed (though you can create it via UI)
-- INSERT INTO users (email, name, role, hotel_name, max_radius, password)
-- VALUES ('admin@sgo.com', 'Admin', 'enterprise', 'SGO Head Office', 99999, 'admin123');
